#include <stdlib.h>
#include <stdio.h>
#include "hash.h"

#define MAX_SONS 4

enum nodeType
{
	ASTREE_DECLARACAO,	
	ASTREE_SYMBOL,	
	ASTREE_PROGRAMA,
	ASTREE_VAR_GLOBAL,
	ASTREE_VAR_GLOBAL_INIT_VEC,
	ASTREE_VAR_GLOBAL_VEC_VALORES,
	ASTREE_LITERAL,
	ASTREE_BYTE_TYPE,
	ASTREE_SHORT_TYPE,
	ASTREE_LONG_TYPE,
	ASTREE_FLOAT_TYPE,
	ASTREE_DOUBLE_TYPE,
	ASTREE_FUNC_CABECALHO,
	ASTREE_FUNCAO,
	ASTREE_LISTA_PARAMETROS,
	ASTREE_MAIS_PARAMETROS,
	ASTREE_BLOCO_COMANDOS,
	ASTREE_LISTA_COMANDOS,
	ASTREE_ATRIBUICAO,
	ASTREE_ATRIBUICAO_VETOR,
	ASTREE_READ,
	ASTREE_PRINT,
	ASTREE_RETURN,
	ASTREE_EXPRESSAO_FUNCAO,
	ASTREE_EXPRESSAO_VETOR,
	ASTREE_IDENTIFIER,
	ASTREE_ADD,
	ASTREE_SUB,
	ASTREE_MUL,
	ASTREE_DIV,
	ASTREE_LESS_THAN,
	ASTREE_GREATER_THAN,
	ASTREE_LE,
	ASTREE_GE,
	ASTREE_EQ,
	ASTREE_NE,
	ASTREE_AND,
	ASTREE_OR,
	ASTREE_LISTA_FUNC_PARAMETROS,
	ASTREE_WHEN_THEN,
	ASTREE_WHEN_THEN_ELSE,
	ASTREE_WHILE,
	ASTREE_FOR,
	ASTREE_PARENTESES,
	ASTREE_COLCHETES,
	ASTREE_NEGATIVO,
	ASTREE_NEGADO,
	ASTREE_DEBUG,
	ASTREE_PRINT_LISTA
};


struct ASTREE
{
	int type;
	int valueType;
	HASH_NODE* symbol;
	struct ASTREE* son[MAX_SONS];
};
typedef struct ASTREE ASTREE;

ASTREE* astreeCreate (int type, HASH_NODE* symbol, ASTREE* son0, ASTREE* son1, ASTREE* son2, ASTREE* son3);
int uncompile(ASTREE* node);
FILE* outfile;
