#include <stdlib.h>
#include <stdio.h>
#include "hash.h"

#define MAX_SONS 4

enum nodeType_e
{
	ASTREE_SYMBOL,	
	ASTREE_PROGRAMA,
	ASTREE_DECLARACAO_VAR_GLOBAL,
	ASTREE_VAR_GLOBAL_INIT_VEC,
	ASTREE_LITERAL,
	ASTREE_BYTE_TYPE,
	ASTREE_SHORT_TYPE,
	ASTREE_LONG_TYPE,
	ASTREE_FLOAT_TYPE,
	ASTREE_DOUBLE_TYPE,
	ASTREE_FUNC_CABECALHO,
	ASTREE_LISTA_PARAMETROS,
	ASTREE_MAIS_PARAMETROS,
	ASTREE_BLOCO_COMANDOS,
	ASTREE_LISTA_COMANDOS,
	ASTREE_ATRIBUICAO,
	ASTREE_READ,
	ASTREE_PRINT,
	ASTREE_RETURN,
	ASTREE_EXPRESSAO,
	ASTREE_EXPRESSAO_IDENTIFIER,
	ASTREE_EXPRESSAO_LITERAL,
	ASTREE_EXPRESSAO_ADD,
	ASTREE_EXPRESSAO_SUB,
	ASTREE_EXPRESSAO_MUL,
	ASTREE_EXPRESSAO_DIV,
	ASTREE_EXPRESSAO_LESS_THAN,
	ASTREE_EXPRESSAO_GREATER_THAN,
	ASTREE_EXPRESSAO_LE,
	ASTREE_EXPRESSAO_GE,
	ASTREE_EXPRESSAO_EQ,
	ASTREE_EXPRESSAO_NE,
	ASTREE_EXPRESSAO_AND,
	ASTREE_EXPRESSAO_OR,
	ASTREE_EXPRESSAO_NEG,
	ASTREE_LISTA_FUNC_PARAMETROS,
	ASTREE_WHEN_THEN,
	ASTREE_WHEN_THEN_ELSE,
	ASTREE_WHILE,
	ASTREE_FOR
};


struct ASTREE
{
	int type;
	HASH_NODE* symbol;
	struct ASTREE* son[MAX_SONS];
};
typedef struct ASTREE ASTREE;


ASTREE* astreeCreate (int type, HASH_NODE* symbol, ASTREE* son0, ASTREE* son1, ASTREE* son2, ASTREE* son3);
void astreePrint(ASTREE* node);
